#Importing packages

In [26]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler, PolynomialFeatures
from sklearn.tree import DecisionTreeClassifier

# importing the dataset

In [27]:
ds = pd.read_csv("heart.csv")
print("Dimention of Dataset", ds.shape,"\n\n")
ds.head()

Dimention of Dataset (1025, 14) 




age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   52    1   0       125   212    0  ...      0      1.0      2   2     3       0
1   53    1   0       140   203    1  ...      1      3.1      0   0     3       0
2   70    1   0       145   174    0  ...      1      2.6      0   0     3       0
3   61    1   0       148   203    0  ...      0      0.0      2   1     3       0
4   62    0   0       138   294    1  ...      0      1.9      1   3     2       0

[5 rows x 14 columns]

# splitting into dependent and independent variables


In [28]:
X = ds.iloc[:, 0:13].values
y = ds.iloc[:, -1].values
X

array([[52.,  1.,  0., ...,  2.,  2.,  3.],
       [53.,  1.,  0., ...,  0.,  0.,  3.],
       [70.,  1.,  0., ...,  0.,  0.,  3.],
       ...,
       [47.,  1.,  0., ...,  1.,  1.,  2.],
       [50.,  0.,  0., ...,  2.,  0.,  2.],
       [54.,  1.,  0., ...,  1.,  1.,  3.]])

In [29]:
y

array([0, 0, 0, ..., 0, 1, 0])

#Splitting into training and testing

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

# Feature Scaling

In [31]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Decision Tree fiiting int the model

In [32]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = "entropy", random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

# Predicting the Test set results

In [33]:
from sklearn.metrics import r2_score
y_pred = classifier.predict(X_test)
print("Model Accuracy: ",r2_score(y_test, y_pred)*100,"%")

Model Accuracy:  100.0 %


# Making the Confusion Matrix

In [34]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[123,   0],
       [  0, 134]])

#Prediction of Heart Disease for random Patients

In [51]:
# 52	1	0	125	212	0	1	168	0	1.0	2	2	3	(Test Input) 
flag = 0
while flag == 0:
    lst = list(map(float, input("Enter [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal] Respectively: ").split()))
    if len(lst) == 13:
      flag = 1
nplst = np.array(lst)
y_pred1 = classifier.predict(nplst.reshape(1,len(nplst)))
print()
if y_pred1 != 0:
  print("Patient have Disease.")
else:
  print("Patient is Normal.")

Enter [age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal] Respectively: 52	1	0	125	212	0	1	168	0	1.0	2	2	3

Patient is Normal.
